### ISSUE TITLE
MyScriptInteractiveInk-Runtime not found

### ISSUE THREAD

**Issue by chy89310** [MyScript/interactive-ink-examples-ios#1]
The dependency `MyScriptInteractiveInk-Runtime (~> 1.0.0)` is not found by CocoaPods when pod install.

**Comment by jnguiavarch** [comment]
Hello @chy89310. Can you please try `pod install --repo-update --verbose` and if the problem persists send us the output.

**Comment by chy89310** [comment]
@jnguiavarch It turns out of my out of date pod repo problem! Thank you for you answer. :)

**Comment by jnguiavarch** [comment]
Can we close this issue then?
