### ISSUE TITLE
myscript::engine::EngineError: INDEX_OUT_OF_BOUNDS

### ISSUE THREAD

**Issue by fankcool** [MyScript/interactive-ink-examples-ios#5]
Hello, I got this exception, does the engine have a cumulative upper limit for a certain period of time? Is there a limit to the concurrency? thanks very much !

**Comment by fankcool** [comment]
My company is a paid user. I have not found such a mistake on the forum. What can I do?

**Comment by fankcool** [comment]
IINKContentPackage partCount() is not nil, but getPartAt(0) get the exception 'myscript::engine::EngineError', reason: 'INDEX_OUT_OF_BOUNDS', can u help me ?

**Comment by MyScriptSupport** [comment]
Dear Fankfank,

I contacted you be email but did not get any answer.
Did you solve the issue?

Best regards,

Olivier

**Comment by fankcool** [comment]
> Dear Fankfank,
> 
> I contacted you be email but did not get any answer.
> Did you solve the issue?
> 
> Best regards,
> 
> Olivier

I did not receive the email, which email address did you send? and now 
I have a new question about svg ：Error, -[IINKEditor export_:mimeType:error:]::507 export operation failed
2019-06-19 06:26:05754 [‼️][MyScriptManager.swift]:279 19 getConvertStr(filePath:) -> Error: 未能完成该操作。Error, -[IINKEditor export_:mimeType:error:]::507 export operation failed

What can I do? My email is locke_fank@126.com, thanks

**Comment by MyScriptSupport** [comment]
Dear Fankfank,

the email was sent to your corporate email address.

Please find the content of it:
_Would you have a call stack when getting the crash? Which function are you calling when it occurs? Is it when calling the getPart function?_

Best regards,

Olivier

**Comment by fankcool** [comment]
When I export svg with text type, not calling getPart function, what platform supports svg ？

**Comment by MyScriptSupport** [comment]
Dear FankFank,

currently, before calling the export function we recommend you call the getSupportedExportMimeTypes function: http://cocoadocs.org/docsets/MyScriptInteractiveInk-Runtime/1.0.0/Classes/IINKEditor.html#//api/name/getSupportedExportMimeTypes:

In the case of a Text part, you can only export as TEXT, JIIX, JPEG, PNG, and not SVG.

Best regards,

Olivier

**Comment by fankcool** [comment]
can i export SVG with Drawing part ?

**Comment by MyScriptSupport** [comment]
Dear FankFank,

currently, only the Diagram mode allows to export as SVG.

Best regards,

Olivier
