### ISSUE TITLE
x and y values of bounding boxes in jiix output

### ISSUE THREAD

**Issue by 0-mykola** [MyScript/interactive-ink-examples-ios#6]
Hi there!

When we try to check jiix output data, x and y coordinates should be in mm format, as from documentation says. But we can't convert this coordinates to pixel format. What formula?

Optional({
    "bounding-box" =     {
        height = "7.8990002";
        width = "55.931087";
        x = "2.8929873";
        y = "11.848503";
    };
    id = 1;
    label = 123;
    type = Text;
    version = 2;
    words =     (
                {
            "bounding-box" =             {
                height = "3.8957596";
                width = "6.0416546";
                x = "2.857316";
                y = "13.697409";
            };
            candidates =             (
                123,
                125,
                723,
                129,
                122
            );
            items =             (
                                {
                    baseline = "0.99999976";
                    "bounding-box" =                     {
                        height = "1.8667965";
                        width = "0.70827675";
                        x = "3.857316";
                        y = "14.697409";
                    };
                    id = 0000030001000700ff00;
                    label = 1;
                    "left-side-bearing" = "-0.32342008";
                    "right-side-bearing" = "1.7434945";
                    timestamp = "2020-05-15 08:23:54.003000";
                    type = glyph;
                    "x-height" = "0.72919601";
                },
                                {
                    baseline = "0.99999976";
                    "bounding-box" =                     {
                        height = "1.8667965";
                        width = "1.2375097";
                        x = "5.155385";
                        y = "14.697409";
                    };
                    id = 0000040001000700ff00;
                    label = 2;
                    "left-side-bearing" = "-0.051063828";
                    "right-side-bearing" = "1.1319149";
                    timestamp = "2020-05-15 08:23:54.787000";
                    type = glyph;
                    "x-height" = "0.72919601";
                },
                                {
                    baseline = "0.98472196";
                    "bounding-box" =                     {
                        height = "1.8957596";
                        width = "1.2664728";
                        x = "6.6324978";
                        y = "14.697409";
                    };
                    id = 0000050001000700ff00;
                    label = 3;
                    "left-side-bearing" = "-0.060291063";
                    "right-side-bearing" = "1.0956341";
                    timestamp = "2020-05-15 08:23:55.828000";
                    type = glyph;
                    "x-height" = "0.71805555";
                }
            );
            label = 123;
        }
    );
})

Another thing.
Data is wrong. X coordinate is always x = "2.857316"; 

I think calculate mechanism of bounding-box are broken. Can you check this?
Thx

**Comment by myscript-developer** [comment]
Dear Nikolay,

thank you for contacting us.

Currently, you shall proceed as indicated in the following post: https://developer-support.myscript.com/support/discussions/topics/16000026410

If you have any question, we recommend you submit these on our forum to get a faster and more accurate answer.

Best regards,
Olivier
