### ISSUE TITLE
MyScriptInteractiveInk-Runtime (= 1.4.1)

### ISSUE THREAD

**Issue by LarryLib** [MyScript/interactive-ink-examples-ios#7]
"......, which depends on MyScriptInteractiveInk-Runtime (= 1.4.1)

None of your spec sources contain a spec satisfying the dependency: `MyScriptInteractiveInk-Runtime (= 1.4.1)`."

When will you add the 1.4.1 tag, and how can I introduce the 1.4.x version through the tag?

**Comment by myscript-developer** [comment]
Dear Larry,
thank you for contacting us.
Indeed, we forgot to add the 1.4.1 tag for our iOS version. You can simply clone from the master (which is basically the 1.4.1 release).
Or you can wait, the tag should be set in the coming hours.
Best regards,
Olivier
